server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/recommendation?useUnicode=true&charactorEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: 123456



# 自定义变量
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/recommendation?useUnicode=true&charactorEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&autoReconnect=true
  database-name: recommendation
  username: root
  password: 123456